import time

from sqlalchemy import inspect, text
from sqlalchemy.exc import OperationalError

from app.core.db import Base, engine
from app.models import Alert, Country, Exploitation, Lot, SensorReading, Warehouse


def _run_post_create_migrations() -> None:
    inspector = inspect(engine)

    with engine.begin() as conn:
        tables = set(inspector.get_table_names())

        if "countries" not in tables:
            conn.execute(
                text(
                    """
                    CREATE TABLE countries (
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      code VARCHAR(3) NOT NULL UNIQUE,
                      name VARCHAR(128) NOT NULL
                    )
                    """
                )
            )
            tables.add("countries")

        if "exploitations" in tables:
            exploitation_columns = {column["name"] for column in inspector.get_columns("exploitations")}
            if "country_id" not in exploitation_columns:
                conn.execute(text("ALTER TABLE exploitations ADD COLUMN country_id INTEGER"))

                # Backfill from legacy columns if present.
                if {"country_code", "country_name"}.issubset(exploitation_columns):
                    conn.execute(
                        text(
                            """
                            INSERT INTO countries (code, name)
                            SELECT DISTINCT country_code, country_name
                            FROM exploitations
                            WHERE country_code IS NOT NULL
                            ON CONFLICT (code) DO NOTHING
                            """
                        )
                    )
                    conn.execute(
                        text(
                            """
                            UPDATE exploitations e
                            SET country_id = c.id
                            FROM countries c
                            WHERE e.country_id IS NULL AND e.country_code = c.code
                            """
                        )
                    )

                conn.execute(
                    text(
                        """
                        INSERT INTO countries (code, name)
                        SELECT DISTINCT 'UNK', 'Unknown'
                        WHERE NOT EXISTS (SELECT 1 FROM countries WHERE code = 'UNK')
                        """
                    )
                )
                conn.execute(
                    text(
                        """
                        UPDATE exploitations
                        SET country_id = (SELECT id FROM countries WHERE code = 'UNK')
                        WHERE country_id IS NULL
                        """
                    )
                )
                conn.execute(text("ALTER TABLE exploitations ALTER COLUMN country_id SET NOT NULL"))

        if "lots" in tables:
            lot_columns = {column["name"] for column in inspector.get_columns("lots")}
            if "planned_dispatch_date" not in lot_columns:
                conn.execute(text("ALTER TABLE lots ADD COLUMN planned_dispatch_date DATE"))
                conn.execute(text("UPDATE lots SET planned_dispatch_date = storage_date + INTERVAL '30 days'"))
            if "actual_dispatch_date" not in lot_columns:
                conn.execute(text("ALTER TABLE lots ADD COLUMN actual_dispatch_date DATE"))


def init_db() -> None:
    _ = (Alert, Country, Exploitation, Lot, SensorReading, Warehouse)
    retries = 20
    delay_seconds = 1
    last_error: Exception | None = None

    for _ in range(retries):
        try:
            Base.metadata.create_all(bind=engine)
            _run_post_create_migrations()
            return
        except OperationalError as exc:
            last_error = exc
            time.sleep(delay_seconds)

    if last_error is not None:
        raise last_error
