import time

from sqlalchemy import inspect, text
from sqlalchemy.exc import OperationalError

from app.core.db import Base, engine
from app.models import AlertCapteur, AlertLot, Country, Exploitation, Lot, SensorReading, Warehouse


def _run_post_create_migrations() -> None:
    inspector = inspect(engine)

    with engine.begin() as conn:
        tables = set(inspector.get_table_names())

        if "alert_lots" not in tables:
            conn.execute(
                text(
                    """
                    CREATE TABLE alert_lots (
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      lot_id INTEGER NOT NULL REFERENCES lots(id),
                      alert_type VARCHAR(64) NOT NULL,
                      message VARCHAR(1024) NOT NULL,
                      email_sent BOOLEAN NOT NULL DEFAULT FALSE,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            tables.add("alert_lots")

        if "alert_capteurs" not in tables:
            conn.execute(
                text(
                    """
                    CREATE TABLE alert_capteurs (
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),
                      alert_type VARCHAR(64) NOT NULL,
                      message VARCHAR(1024) NOT NULL,
                      email_sent BOOLEAN NOT NULL DEFAULT FALSE,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            tables.add("alert_capteurs")

        if "countries" not in tables:
            conn.execute(
                text(
                    """
                    CREATE TABLE countries (
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      code VARCHAR(3) NOT NULL UNIQUE,
                      name VARCHAR(128) NOT NULL
                    )
                    """
                )
            )
            tables.add("countries")

        if "exploitations" in tables:
            exploitation_columns = {column["name"] for column in inspector.get_columns("exploitations")}
            if "country_id" not in exploitation_columns:
                conn.execute(text("ALTER TABLE exploitations ADD COLUMN country_id INTEGER"))

                # Backfill from legacy columns if present.
                if {"country_code", "country_name"}.issubset(exploitation_columns):
                    conn.execute(
                        text(
                            """
                            INSERT INTO countries (code, name)
                            SELECT DISTINCT country_code, country_name
                            FROM exploitations
                            WHERE country_code IS NOT NULL
                            ON CONFLICT (code) DO NOTHING
                            """
                        )
                    )
                    conn.execute(
                        text(
                            """
                            UPDATE exploitations e
                            SET country_id = c.id
                            FROM countries c
                            WHERE e.country_id IS NULL AND e.country_code = c.code
                            """
                        )
                    )

                conn.execute(
                    text(
                        """
                        INSERT INTO countries (code, name)
                        SELECT DISTINCT 'UNK', 'Unknown'
                        WHERE NOT EXISTS (SELECT 1 FROM countries WHERE code = 'UNK')
                        """
                    )
                )
                conn.execute(
                    text(
                        """
                        UPDATE exploitations
                        SET country_id = (SELECT id FROM countries WHERE code = 'UNK')
                        WHERE country_id IS NULL
                        """
                    )
                )
                conn.execute(text("ALTER TABLE exploitations ALTER COLUMN country_id SET NOT NULL"))

        if "lots" in tables:
            lot_columns = {column["name"] for column in inspector.get_columns("lots")}
            if "planned_dispatch_date" not in lot_columns:
                conn.execute(text("ALTER TABLE lots ADD COLUMN planned_dispatch_date DATE"))
                conn.execute(text("UPDATE lots SET planned_dispatch_date = storage_date + INTERVAL '30 days'"))
            if "actual_dispatch_date" not in lot_columns:
                conn.execute(text("ALTER TABLE lots ADD COLUMN actual_dispatch_date DATE"))

        if "warehouses" in tables:
            warehouse_columns = {column["name"] for column in inspector.get_columns("warehouses")}
            # Backward compatibility: legacy schema used ideal_temp instead of ideal_temperature.
            if "ideal_temperature" not in warehouse_columns:
                conn.execute(text("ALTER TABLE warehouses ADD COLUMN ideal_temperature DOUBLE PRECISION"))
                if "ideal_temp" in warehouse_columns:
                    conn.execute(
                        text(
                            "UPDATE warehouses SET ideal_temperature = ideal_temp "
                            "WHERE ideal_temperature IS NULL"
                        )
                    )
                conn.execute(text("UPDATE warehouses SET ideal_temperature = 0.0 WHERE ideal_temperature IS NULL"))
                conn.execute(text("ALTER TABLE warehouses ALTER COLUMN ideal_temperature SET NOT NULL"))

            # Backward compatibility: legacy schema used single tolerance fields.
            if "temperature_tolerance_low" not in warehouse_columns:
                conn.execute(text("ALTER TABLE warehouses ADD COLUMN temperature_tolerance_low DOUBLE PRECISION"))
                if "temperature_tolerance" in warehouse_columns:
                    conn.execute(
                        text(
                            "UPDATE warehouses SET temperature_tolerance_low = temperature_tolerance "
                            "WHERE temperature_tolerance_low IS NULL"
                        )
                    )
                conn.execute(text("UPDATE warehouses SET temperature_tolerance_low = 3.0 WHERE temperature_tolerance_low IS NULL"))
                conn.execute(text("ALTER TABLE warehouses ALTER COLUMN temperature_tolerance_low SET NOT NULL"))

            if "temperature_tolerance_high" not in warehouse_columns:
                conn.execute(text("ALTER TABLE warehouses ADD COLUMN temperature_tolerance_high DOUBLE PRECISION"))
                if "temperature_tolerance" in warehouse_columns:
                    conn.execute(
                        text(
                            "UPDATE warehouses SET temperature_tolerance_high = temperature_tolerance "
                            "WHERE temperature_tolerance_high IS NULL"
                        )
                    )
                conn.execute(text("UPDATE warehouses SET temperature_tolerance_high = 3.0 WHERE temperature_tolerance_high IS NULL"))
                conn.execute(text("ALTER TABLE warehouses ALTER COLUMN temperature_tolerance_high SET NOT NULL"))

            if "humidity_tolerance_low" not in warehouse_columns:
                conn.execute(text("ALTER TABLE warehouses ADD COLUMN humidity_tolerance_low DOUBLE PRECISION"))
                if "humidity_tolerance" in warehouse_columns:
                    conn.execute(
                        text(
                            "UPDATE warehouses SET humidity_tolerance_low = humidity_tolerance "
                            "WHERE humidity_tolerance_low IS NULL"
                        )
                    )
                conn.execute(text("UPDATE warehouses SET humidity_tolerance_low = 2.0 WHERE humidity_tolerance_low IS NULL"))
                conn.execute(text("ALTER TABLE warehouses ALTER COLUMN humidity_tolerance_low SET NOT NULL"))

            if "humidity_tolerance_high" not in warehouse_columns:
                conn.execute(text("ALTER TABLE warehouses ADD COLUMN humidity_tolerance_high DOUBLE PRECISION"))
                if "humidity_tolerance" in warehouse_columns:
                    conn.execute(
                        text(
                            "UPDATE warehouses SET humidity_tolerance_high = humidity_tolerance "
                            "WHERE humidity_tolerance_high IS NULL"
                        )
                    )
                conn.execute(text("UPDATE warehouses SET humidity_tolerance_high = 2.0 WHERE humidity_tolerance_high IS NULL"))
                conn.execute(text("ALTER TABLE warehouses ALTER COLUMN humidity_tolerance_high SET NOT NULL"))


def init_db() -> None:
    _ = (AlertCapteur, AlertLot, Country, Exploitation, Lot, SensorReading, Warehouse)
    retries = 20
    delay_seconds = 1
    last_error: Exception | None = None

    for _ in range(retries):
        try:
            Base.metadata.create_all(bind=engine)
            _run_post_create_migrations()
            return
        except OperationalError as exc:
            last_error = exc
            time.sleep(delay_seconds)

    if last_error is not None:
        raise last_error
